version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASSERTION_CLIENT_MOCK_ENABLED : false
      IDP_CLIENT_MOCK_ENABLED: false
      IDP_CLIENT_BASE_URI: "http://localhost:3001"
      LOLLIPOP_ASSERTION_NOT_BEFORE_DATE_FORMAT: "yyyy-MM-dd'T'HH:mm:ss'Z'"
      LOLLIPOP_ASSERTION_INSTANT_DATE_FORMAT: "yyyy-MM-dd'T'HH:mm:ss'Z'"