FROM amazoncorretto:11@sha256:ad62c0f683aed0af8a92f1a0b5847b21675d26aeff15f9177857fbcc8cfb27f8

RUN yum update -y --security
RUN mkdir /app

COPY core/build/libs/*.jar /app/
COPY http-verifier/build/libs/*.jar /app/
COPY redis-storage/build/libs/*.jar /app/
COPY identity-service-rest-client-native/build/libs/*.jar /app/
COPY assertion-rest-client-native/build/libs/*.jar /app/