version: "3.9"
services:
  mockserverAssertion:
    image: mockoon/cli:latest
    command: [ "--data", "data", "--port", "3000" ]
    volumes:
      - ./e2e/mockoon/mockoonAssertions.json:/data:readonly
  mockserverIDP:
    image: mockoon/cli:latest
    command: [ "--data", "data", "--port", "3001" ]
    volumes:
      - ./e2e/mockoon/mockoonIDP.json:/data:readonly
  web:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 15s
    environment:
      ##Client mocks config
      ASSERTION_CLIENT_MOCK_ENABLED: ${ASSERTION_CLIENT_MOCK_ENABLED:-false}
      IDP_CLIENT_MOCK_ENABLED: ${IDP_CLIENT_MOCK_ENABLED:-false}

      ##Sample controller endpoint
      SAMPLE_LOLLIPOP_CONSUMER_ENDPOINT: ${SAMPLE_LOLLIPOP_CONSUMER_ENDPOINT:-/api/v1/lollipop-consumer}

      ##General Lollipop Configs Sample
      LOLLIPOP_ASSERTION_EXPIRE_IN_DAYS: ${LOLLIPOP_ASSERTION_EXPIRE_IN_DAYS:-180}
      LOLLIPOP_EXPECTED_LC_ORIGINAL_URL: ${LOLLIPOP_EXPECTED_LC_ORIGINAL_URL:-https://api-app.io.pagopa.it/first-lollipop/sign}
      LOLLIPOP_EXPECTED_LC_ORIGINAL_METHOD: ${LOLLIPOP_EXPECTED_LC_ORIGINAL_METHOD:-POST}
      LOLLIPOP_ASSERTION_NOT_BEFORE_DATE_FORMAT: ${LOLLIPOP_ASSERTION_NOT_BEFORE_DATE_FORMAT:-yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
      LOLLIPOP_ASSERTION_INSTANT_DATE_FORMAT: ${LOLLIPOP_ASSERTION_INSTANT_DATE_FORMAT:-yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}

      ###Idp Client Configs
      IDP_CLIENT_CIEID: ${IDP_CLIENT_CIEID:-https://idserver.servizicie.interno.gov.it/idp/profile/SAML2/POST/SSO}
      IDP_CLIENT_BASE_URI: ${IDP_CLIENT_BASE_URI:-https://api.is.eng.pagopa.it}
      IDP_CLIENT_CIE_ENDPOINT: ${IDP_CLIENT_CIE_ENDPOINT:-/idp-keys/cie}
      IDP_CLIENT_SPID_ENDPOINT: ${IDP_CLIENT_SPID_ENDPOINT:-/idp-keys/spid}

      ###Idp Storage Configs
      IDP_STORAGE_ENABLED: ${IDP_STORAGE_ENABLED:-true}
      IDP_STORAGE_EVICTION_DELAY: ${IDP_STORAGE_EVICTION_DELAY:-1}

      ##Assertion Client Configs
      ASSERTION_REST_URI: ${ASSERTION_REST_URI:-http://localhost:3000}
      ASSERTION_REST_ENDPOINT: ${ASSERTION_REST_ENDPOINT:-/assertions}

      ##Assertion Storage Configs
      ASSERTION_STORAGE_ENABLED: ${ASSERTION_STORAGE_ENABLED:-true}
      ASSERTION_STORAGE_EVICTION_DELAY: ${ASSERTION_STORAGE_EVICTION_DELAY:-1}


