FROM amazoncorretto:11@sha256:6955c57192a10a018aedef9d0b9adf2e23e9a2e839ebd4007bcc65becadf25a3

RUN yum update -y --security
RUN mkdir /app

COPY core/build/libs/*.jar /app/
COPY http-verifier/build/libs/*.jar /app/
COPY redis-storage/build/libs/*.jar /app/
COPY identity-service-rest-client-native/build/libs/*.jar /app/
COPY assertion-rest-client-native/build/libs/*.jar /app/