FROM amazoncorretto:11@sha256:731c45b6f5245537ccd8a764a810af83dc4a5f0cac3349c13d49555b1ae341cc

RUN yum update -y --security
RUN mkdir /app

COPY core/build/libs/*.jar /app/
COPY http-verifier/build/libs/*.jar /app/
COPY redis-storage/build/libs/*.jar /app/
COPY identity-service-rest-client-native/build/libs/*.jar /app/
COPY assertion-rest-client-native/build/libs/*.jar /app/