/*
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.pagopa.tech.lollipop.consumer.idp.client.simple.internal.model;

import java.util.StringJoiner;
import java.util.Map;
import java.util.HashMap;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import it.pagopa.tech.lollipop.consumer.idp.client.simple.internal.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-11T16:21:49.277208500+02:00[Europe/Paris]")
@JsonDeserialize(using = CertData.CertDataDeserializer.class)
@JsonSerialize(using = CertData.CertDataSerializer.class)
public class CertData extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CertData.class.getName());

    public static class CertDataSerializer extends StdSerializer<CertData> {
        public CertDataSerializer(Class<CertData> t) {
            super(t);
        }

        public CertDataSerializer() {
            this(null);
        }

        @Override
        public void serialize(CertData value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CertDataDeserializer extends StdDeserializer<CertData> {
        public CertDataDeserializer() {
            this(CertData.class);
        }

        public CertDataDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CertData deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize CIECertData
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (CIECertData.class.equals(Integer.class) || CIECertData.class.equals(Long.class) || CIECertData.class.equals(Float.class) || CIECertData.class.equals(Double.class) || CIECertData.class.equals(Boolean.class) || CIECertData.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((CIECertData.class.equals(Integer.class) || CIECertData.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((CIECertData.class.equals(Float.class) || CIECertData.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (CIECertData.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (CIECertData.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CIECertData.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    if (((CIECertData) deserialized).getEntityDescriptor() != null) {
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'CIECertData'");
                    }
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CIECertData'", e);
            }

            // deserialize SPIDCertData
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SPIDCertData.class.equals(Integer.class) || SPIDCertData.class.equals(Long.class) || SPIDCertData.class.equals(Float.class) || SPIDCertData.class.equals(Double.class) || SPIDCertData.class.equals(Boolean.class) || SPIDCertData.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SPIDCertData.class.equals(Integer.class) || SPIDCertData.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SPIDCertData.class.equals(Float.class) || SPIDCertData.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SPIDCertData.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SPIDCertData.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SPIDCertData.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    if(((SPIDCertData) deserialized).getEntitiesDescriptor() != null){
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SPIDCertData'");
                    }
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SPIDCertData'", e);
            }

            if (match == 1) {
                CertData ret = new CertData();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for CertData: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CertData getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CertData cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public CertData() {
        super("oneOf", Boolean.FALSE);
    }

    public CertData(CIECertData o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CertData(SPIDCertData o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CIECertData", CIECertData.class);
        schemas.put("SPIDCertData", SPIDCertData.class);
        JSON.registerDescendants(CertData.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CertData.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CIECertData, SPIDCertData
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(CIECertData.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SPIDCertData.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CIECertData, SPIDCertData");
    }

    /**
     * Get the actual instance, which can be the following:
     * CIECertData, SPIDCertData
     *
     * @return The actual instance (CIECertData, SPIDCertData)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CIECertData`. If the actual instance is not `CIECertData`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CIECertData`
     * @throws ClassCastException if the instance is not `CIECertData`
     */
    public CIECertData getCIECertData() throws ClassCastException {
        return (CIECertData)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SPIDCertData`. If the actual instance is not `SPIDCertData`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SPIDCertData`
     * @throws ClassCastException if the instance is not `SPIDCertData`
     */
    public SPIDCertData getSPIDCertData() throws ClassCastException {
        return (SPIDCertData)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof CIECertData) {
        if (getActualInstance() != null) {
          joiner.add(((CIECertData)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SPIDCertData) {
        if (getActualInstance() != null) {
          joiner.add(((SPIDCertData)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

