/*
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.pagopa.tech.lollipop.consumer.idp.client.simple.internal.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;

import java.util.Map;


/**
 * EntityDescriptor
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
public class EntityDescriptor {
    @JsonProperty("entityID")
    private String entityID;

    private String signature;

    @SuppressWarnings("unchecked")
    @JsonProperty("Signature")
    private void unpackNestedSignature(Map<String, Object> signature) {
        Map<String, Object> keyInfo = (Map<String, Object>) signature.get("KeyInfo");
        Map<String, Object> x509Data = (Map<String, Object>) keyInfo.get("X509Data");
        this.signature = (String) x509Data.get("X509Certificate");
    }

}

