/*
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.pagopa.tech.lollipop.consumer.idp.client.simple.internal.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;


/**
 * EntityDescriptor
 */
@JsonPropertyOrder({
  EntityDescriptor.JSON_PROPERTY_ENTITY_I_D
})
@JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-11T16:21:49.277208500+02:00[Europe/Paris]")
public class EntityDescriptor {
  public static final String JSON_PROPERTY_ENTITY_I_D = "entityID";
  private String entityID;

  public EntityDescriptor() { 
  }

  public EntityDescriptor entityID(String entityID) {
    this.entityID = entityID;
    return this;
  }

   /**
   * Get entityID
   * @return entityID
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITY_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntityID() {
    return entityID;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntityID(String entityID) {
    this.entityID = entityID;
  }


  /**
   * Return true if this EntityDescriptor object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityDescriptor entityDescriptor = (EntityDescriptor) o;
    return Objects.equals(this.entityID, entityDescriptor.entityID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityDescriptor {\n");
    sb.append("    entityID: ").append(toIndentedString(entityID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `entityID` to the URL query string
    if (getEntityID() != null) {
      joiner.add(String.format("%sentityID%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEntityID()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

