/*
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.pagopa.tech.lollipop.consumer.idp.client.simple.internal.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;
import java.util.StringJoiner;


/**
 * SPIDCertData
 */
@JsonPropertyOrder({
  SPIDCertData.JSON_PROPERTY_ENTITIES_DESCRIPTOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-11T16:21:49.277208500+02:00[Europe/Paris]")
public class SPIDCertData {
  public static final String JSON_PROPERTY_ENTITIES_DESCRIPTOR = "entitiesDescriptor";
  private SPIDCertDataEntitiesDescriptor entitiesDescriptor;

  public SPIDCertData() { 
  }

  public SPIDCertData entitiesDescriptor(SPIDCertDataEntitiesDescriptor entitiesDescriptor) {
    this.entitiesDescriptor = entitiesDescriptor;
    return this;
  }

   /**
   * Get entitiesDescriptor
   * @return entitiesDescriptor
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITIES_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SPIDCertDataEntitiesDescriptor getEntitiesDescriptor() {
    return entitiesDescriptor;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntitiesDescriptor(SPIDCertDataEntitiesDescriptor entitiesDescriptor) {
    this.entitiesDescriptor = entitiesDescriptor;
  }


  /**
   * Return true if this SPIDCertData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SPIDCertData spIDCertData = (SPIDCertData) o;
    return Objects.equals(this.entitiesDescriptor, spIDCertData.entitiesDescriptor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entitiesDescriptor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SPIDCertData {\n");
    sb.append("    entitiesDescriptor: ").append(toIndentedString(entitiesDescriptor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `entitiesDescriptor` to the URL query string
    if (getEntitiesDescriptor() != null) {
      joiner.add(getEntitiesDescriptor().toUrlQueryString(prefix + "entitiesDescriptor" + suffix));
    }

    return joiner.toString();
  }
}

