/* (C)2023 */
package it.pagopa.tech.lollipop.consumer;

public class TestUtils {

    public static final String VALID_FISCAL_CODE = "AAAAAA89S20I111X";
    public static final String VALID_JWK =
            "{  \"kty\": \"EC\",  \"crv\": \"P-256\",  \"x\":"
                    + " \"SVqB4JcUD6lsfvqMr-OKUNUphdNn64Eay60978ZlL74\",  \"y\":"
                    + " \"lf0u0pMj4lGAzZix5u4Cm5CMQIgMNpkwy163wtKYVKI\"}";
    public static final String VALID_SHA_256_ASSERTION_REF =
            "sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg";
    public static final String VALID_SHA_384_ASSERTION_REF =
            "sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw";
    public static final String VALID_SHA_512_ASSERTION_REF =
            "sha512-nX5CfUc5R-FoYKYZwvQMuc4Tt-heb7vHi_O-AMUSqHNVCw9kNaN2SVuN-DXtGXyUhrcVcQdCyY6FVzl_vyWXNA";
    public static final String EMPTY_ASSERTION_XML =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><root></root>";
    public static final String ASSERTION_XML_WITH_INVALID_PERIOD_DATE_FORMAT =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\"><saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\"><saml2:Conditions"
                + " NotBefore=\"2023-02-28Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\"><saml2:AudienceRestriction><saml2:Audience>https://app-backend.io.italia.it</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions></saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_EXPIRED_PERIOD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\"><saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\"><saml2:Conditions"
                + " NotBefore=\"2000-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\"><saml2:AudienceRestriction><saml2:Audience>https://app-backend.io.italia.it</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions></saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_ATTRIBUTE_TAG =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\"><saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\"><saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\"><saml2:AudienceRestriction><saml2:Audience>https://app-backend.io.italia.it</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions></saml2:Assertion></saml2p:Response>";

    public static final String ASSERTION_XML_WITHOUT_FISCAL_CODE =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">     "
                + " <saml2:Conditions NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">         <saml2:AudienceRestriction> "
                + "           <saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>    "
                + "     </saml2:AudienceRestriction>      </saml2:Conditions>\t       "
                + " <saml2:AttributeStatement>         <saml2:Attribute>         </saml2:Attribute>"
                + "      </saml2:AttributeStatement>   </saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_SUBJECTCONFIRMATIONDATA_TAG =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">     "
                + " <saml2:Conditions NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">         <saml2:AudienceRestriction> "
                + "           <saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>    "
                + "     </saml2:AudienceRestriction>      </saml2:Conditions>\t "
                + " <saml2:AttributeStatement>         <saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">            <saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>        "
                + " </saml2:Attribute>      </saml2:AttributeStatement>  "
                + " </saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_INVALID_INRESPONSETO_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"INVALIDsha-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_INRESPONSETO_SHA256_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_INRESPONSETO_SHA384_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_INRESPONSETO_SHA512_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha512-nX5CfUc5R-FoYKYZwvQMuc4Tt-heb7vHi_O-AMUSqHNVCw9kNaN2SVuN-DXtGXyUhrcVcQdCyY6FVzl_vyWXNA\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha512-nX5CfUc5R-FoYKYZwvQMuc4Tt-heb7vHi_O-AMUSqHNVCw9kNaN2SVuN-DXtGXyUhrcVcQdCyY6FVzl_vyWXNA\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_INSTANT_FIELD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\" Version=\"2.0\">\t"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_ENTITY_ID_FIELD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_INVALID_INSTANT_FORMAT =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"1680691737\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\" IssueInstant=\"1680691737\""
                + " Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer>"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_ENTITY_ID_FIELD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer>"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_INVALID_SIGNATURE =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer><Signature"
                + " xmlns=\"http://www.w3.org/2000/09/xmldsig#\">\n"
                + "         <SignedInfo>\n"
                + "            <CanonicalizationMethod"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\" />\n"
                + "            <SignatureMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\" />\n"
                + "            <Reference URI=\"#_6b9580aa-08b1-4f19-8fb6-8b670d070bad\">\n"
                + "               <Transforms>\n"
                + "                  <Transform"
                + " Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\" />\n"
                + "                  <Transform"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\" />\n"
                + "               </Transforms>\n"
                + "               <DigestMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\" />\n"
                + "              "
                + " <DigestValue>ViSjPfKj683dCuO7FdSzbQjw+vECYfoxgTeiVSgxr+I=</DigestValue>\n"
                + "            </Reference>\n"
                + "         </SignedInfo>\n"
                + "        "
                + " <SignatureValue>O9lmrtHPudDz2fzzNH3DQxWy2rlXE56G54Siq7OPMYwps/cyo3wKo7+PwMJYNhhz1l57OYJ5e/MF\n"
                + "               "
                + " ctVtYyl2rWo3QZOidWhg8WINIEqtFXIpk+ht5i2t3P1132/iL/gnY+fgemhnbOV/otEspHA4Wsio\n"
                + "               "
                + " I8xWjekAFlHBTOTtO9vzzqTtf+yalf+6pZmRLtOYrMMV4W3QZ2oLr7C2vTgcl5eVXJyGf0U8Y2bf\n"
                + "               "
                + " 7OPRHJNnVs4S8ztWQEwqZLFA1SvyCx1Nx6f+xd9lT7Lo1h81MRMdvRTk3rAaWYaqAmU9mxVnzsw4\n"
                + "                xaLjxR4rE2drY3eb+O8uHZbzFlOhPtaINRPILg==</SignatureValue>\n"
                + "         <KeyInfo>\n"
                + "            <X509Data>\n"
                + "              "
                + " <X509Certificate>MIIFgzCCA2ugAwIBAgIIJSppAZKg/XQwDQYJKoZIhvcNAQELBQAwZTELMAkGA1UEBhMCSVQxHjAc\n"
                + "                       "
                + " BgNVBAoMFVBvc3RlIEl0YWxpYW5lIFMucC5BLjEaMBgGA1UEYQwRVkFUSVQtMDExMTQ2MDEwMDYx\n"
                + "                       "
                + " GjAYBgNVBAMMEVBvc3RlIEl0YWxpYW5lIENBMB4XDTIxMDIxODExNDYzMVoXDTI0MDIxOTExNDYz\n"
                + "                       "
                + " MVowQzELMAkGA1UEBhMCSVQxHjAcBgNVBAoMFVBvc3RlIEl0YWxpYW5lIFMucC5BLjEUMBIGA1UE\n"
                + "                       "
                + " AwwLaWRwLXBvc3RlaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZFEtJoEHFAjpC\n"
                + "                       "
                + " aZcj5DVWrRDyaLZyu31XApslbo87CyWz61OJMtw6QQU0MdCtrYbtSJ6vJwx7/6EUjsZ3u4x3EPLd\n"
                + "                       "
                + " lkyiGOqukPwATv4c7TVOUVs5onIqTphM9b+AHRg4ehiMGesm/9d7RIaLuN79iPUvdLn6WP3idAfE\n"
                + "                       "
                + " w+rhJ/wYEQ0h1Xm5osNUgtWcBGavZIjLssWNrDDfJYxXH3QZ0kI6feEvLCJwgjXLGkBuhFehNhM4\n"
                + "                       "
                + " fhbX9iUCWwwkJ3JsP2++Rc/iTA0LZhiUsXNNq7gBcLAJ9UX2V1dWjTzBHevfHspzt4e0VgIIwbDR\n"
                + "                       "
                + " qsRtF8VUPSDYYbLoqwbLt18XAgMBAAGjggFXMIIBUzA/BggrBgEFBQcBAQQzMDEwLwYIKwYBBQUH\n"
                + "                       "
                + " MAGGI2h0dHA6Ly9wb3N0ZWNlcnQucG9zdGUuaXQvcGktb2NzcENBMB0GA1UdDgQWBBRL64pGUJHw\n"
                + "                       "
                + " Y7ok6cRMUgXvMBoLMjAfBgNVHSMEGDAWgBRs0025F7hHd0d+ULyAaELPZ7w/eTA+BgNVHSAENzA1\n"
                + "                       "
                + " MDMGCCtMMAEFAQEEMCcwJQYIKwYBBQUHAgEWGWh0dHA6Ly9wb3N0ZWNlcnQucG9zdGUuaXQwOAYD\n"
                + "                       "
                + " VR0fBDEwLzAtoCugKYYnaHR0cDovL3Bvc3RlY2VydC5wb3N0ZS5pdC9waS1DQS9jcmwuY3JsMA4G\n"
                + "                       "
                + " A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwJwYDVR0RBCAwHoEc\n"
                + "                       "
                + " aWRwLXBvc3RlaWRAcG9zdGVpdGFsaWFuZS5pdDANBgkqhkiG9w0BAQsFAAOCAgEAp0EhITlTx+cO\n"
                + "                       "
                + " aoXw//nBl6Q4y82MfSGfPJIw3ROV1z3tHBctaksi/RxAzyMD5beO2s8Q6lXx0sLMCcuUQmzHj3eJ\n"
                + "                       "
                + " bqn+6sIUr000dSlX/iPgVUc2dvPIZZg9xu38J8NvCfrtgAGY5iMVFMd3CZLFw0ybr+Bx/1K/NhQO\n"
                + "                       "
                + " 7jxn0RSGA1J4mM2syVhEDUODs9kz3T4kXYUofwwvPL1a9xB9RBqbp7plYtbBBdftEORUQrWzH1mz\n"
                + "                       "
                + " NO4nlFkX9qgVrgFIIJJT2KadHoop1r65O9ffncK14qpNo3eTsNDq3hRlteb7ylmlJ8CoakUWZeXD\n"
                + "                       "
                + " DP9ZboWxZkyp+9903OrToRvOgeWSc+YrqcRZOv7r6tTALTk4U9OTKDG9/eNWSGQqD7Qd/9rssfF0\n"
                + "                       "
                + " uJEGHnbsk/Hvdxn8apgWN1Zwt6tsT7f/DO0Pdlaso9g7PVy8R+B3VkWAh76uCcICIPFBluC/ljaH\n"
                + "                       "
                + " V8hI+VsCLpMClo83YMCEM6E6nAPD22+fDR/DF9P73P04yUvJVHx4cnHPrpxVrPbaJoKrr9mUOLFy\n"
                + "                       "
                + " VRekX78ZRgiFiKYDNsiq9+148oRy+VehpmBoQ+T2EPeDFQ8JJ4xT8H7qdyr1swSk/9Lu4K0kw/yC\n"
                + "                       "
                + " TSb9K/wCuiHiuoSB54rzJoQxz90gS868r/+JGahYwHY5dUh1RbA4g5N8H3TDThc=</X509Certificate>\n"
                + "            </X509Data>\n"
                + "         </KeyInfo>\n"
                + "      </Signature>\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String VALID_IDP_CERTIFICATE =
            "MIIC7TCCAdWgAwIBAgIJAMbxPOoBth1LMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNV\n"
                    + "BAYTAklUMB4XDTE4MDkwNDE0MDAxM1oXDTE4MTAwNDE0MDAxM1owDTELMAkGA1UE\n"
                    + "BhMCSVQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJrW3y8Zd2jESP\n"
                    + "XGMRY04cHC4Qfo3302HEY1C6x1aDfW7aR/tXzNplfdw8ZtZugSSmHZBxVrR8aA08\n"
                    + "dUVbbtUw5qD0uAWKIeREqGfhM+J1STAMSI2/ZxA6t2fLmv8l1eRd1QGeRDm7yF9E\n"
                    + "EKGY9iUZD3LJf2mWdVBAzzYlG23M769k+9JuGZxuviNWMjojgYRiQFgzypUJJQz+\n"
                    + "Ihh3q7LMjjiQiiULVb9vnJg7UdU9Wf3xGRkxk6uiGP9SzWigSObUekYYQ4ZAI/sp\n"
                    + "ILywgDxVMMtv/eVniUFKLABtljn5cE9zltECahPbm7wIuMJpDDu5GYHGdYO0j+K7\n"
                    + "fhjvF2mzAgMBAAGjUDBOMB0GA1UdDgQWBBQEVmzA/L1/fd70ok+6xtDRF8A3HjAf\n"
                    + "BgNVHSMEGDAWgBQEVmzA/L1/fd70ok+6xtDRF8A3HjAMBgNVHRMEBTADAQH/MA0G\n"
                    + "CSqGSIb3DQEBCwUAA4IBAQCRMo4M4PqS0iLTTRWfikMF4hYMapcpmuna6p8aee7C\n"
                    + "wTjS5y7y18RLvKTi9l8OI0dVkgokH8fq8/o13vMw4feGxro1hMeUilRtH52funrW\n"
                    + "C+FgPrqk3o/8cZOnq+CqnFFDfILLiEb/PVJMddvTXgv2f9O6u17f8GmMLzde1yvY\n"
                    + "Da1fG/Pi0fG2F0yw/CmtP8OTLSvxjPtJ+ZckGzZa9GotwHsoVJ+Od21OU2lOeCnO\n"
                    + "jJOAbewHgqwkCB4O4AT5RM4ThAQtoU8QibjD1XDk/ZbEHdKcofnziDyl0V8gglP2\n"
                    + "SxpzDaPX0hm4wgHk9BOtSikb72tfOw+pNfeSrZEr6ItQ";
    public static final String VALID_ASSERTION_XML =
            "<samlp:Response xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" Version=\"2.0\""
                + " ID=\"id_432ca7e6e3fb172b94de5944e6cc0716b08227e7\""
                + " IssueInstant=\"2023-04-26T13:23:47Z\""
                + " Destination=\"https://localhost:8000/assertionConsumerService\""
                + " InResponseTo=\"sha256-chG21HBOK-wJp2hHuYPrx7tAII2UGWVF-IFo0crUOtw\">\n"
                + "  <saml:Issuer xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\""
                + " NameQualifier=\"https://spid-testenv2:8088\">https://spid-testenv2:8088</saml:Issuer><ds:Signature"
                + " xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:SignedInfo><ds:CanonicalizationMethod"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/><ds:SignatureMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\"/><ds:Reference"
                + " URI=\"#id_432ca7e6e3fb172b94de5944e6cc0716b08227e7\"><ds:Transforms><ds:Transform"
                + " Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/><ds:Transform"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/></ds:Transforms><ds:DigestMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\"/><ds:DigestValue>s/DqYePHC7eCXX5ncsiFYNLyKbzS6P5C8331H1b8e30=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>WcasorooElvhmK0kxFUdBVCqyRYi0SCNGRSZZnC9Q2sZHOYGZbERe4/T8OSuRKbSrEivXIHRgNr8WskZTM2CiywfWChHfGvhERsLuPJE8oh9CR3eicX/eg0ynJqwx4IoYhTb2NOwqMFc66nnutMhG/Smdtjs4SFz0RQYYVeZ5Ho51iTHd94uBV9ZHXjqcvs3EitUsJ0Zg1Pkw352tt8y7niUcGjAd8nydI72S12sF5ePv05AunFp7vZpYbKqi62fQLORCn1ZP7WKFD75hL0bCvZaSRF285GkfSnLfe1S4tLff2SlTQWevOMU/wCkHJmQwHT1LMwcWRnMvv4V+vd1XQ==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIC7TCCAdWgAwIBAgIJAMbxPOoBth1LMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNV\n"
                + "BAYTAklUMB4XDTE4MDkwNDE0MDAxM1oXDTE4MTAwNDE0MDAxM1owDTELMAkGA1UE\n"
                + "BhMCSVQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJrW3y8Zd2jESP\n"
                + "XGMRY04cHC4Qfo3302HEY1C6x1aDfW7aR/tXzNplfdw8ZtZugSSmHZBxVrR8aA08\n"
                + "dUVbbtUw5qD0uAWKIeREqGfhM+J1STAMSI2/ZxA6t2fLmv8l1eRd1QGeRDm7yF9E\n"
                + "EKGY9iUZD3LJf2mWdVBAzzYlG23M769k+9JuGZxuviNWMjojgYRiQFgzypUJJQz+\n"
                + "Ihh3q7LMjjiQiiULVb9vnJg7UdU9Wf3xGRkxk6uiGP9SzWigSObUekYYQ4ZAI/sp\n"
                + "ILywgDxVMMtv/eVniUFKLABtljn5cE9zltECahPbm7wIuMJpDDu5GYHGdYO0j+K7\n"
                + "fhjvF2mzAgMBAAGjUDBOMB0GA1UdDgQWBBQEVmzA/L1/fd70ok+6xtDRF8A3HjAf\n"
                + "BgNVHSMEGDAWgBQEVmzA/L1/fd70ok+6xtDRF8A3HjAMBgNVHRMEBTADAQH/MA0G\n"
                + "CSqGSIb3DQEBCwUAA4IBAQCRMo4M4PqS0iLTTRWfikMF4hYMapcpmuna6p8aee7C\n"
                + "wTjS5y7y18RLvKTi9l8OI0dVkgokH8fq8/o13vMw4feGxro1hMeUilRtH52funrW\n"
                + "C+FgPrqk3o/8cZOnq+CqnFFDfILLiEb/PVJMddvTXgv2f9O6u17f8GmMLzde1yvY\n"
                + "Da1fG/Pi0fG2F0yw/CmtP8OTLSvxjPtJ+ZckGzZa9GotwHsoVJ+Od21OU2lOeCnO\n"
                + "jJOAbewHgqwkCB4O4AT5RM4ThAQtoU8QibjD1XDk/ZbEHdKcofnziDyl0V8gglP2\n"
                + "SxpzDaPX0hm4wgHk9BOtSikb72tfOw+pNfeSrZEr6ItQ\n"
                + "</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature>\n"
                + "  <samlp:Status>\n"
                + "    <samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Success\"/>\n"
                + "  </samlp:Status>\n"
                + "  <saml:Assertion xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" Version=\"2.0\""
                + " ID=\"id_451563f4726745384be4ab177e82c542baa99430\""
                + " IssueInstant=\"2023-04-26T13:23:47Z\">\n"
                + "    <saml:Issuer Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\""
                + " NameQualifier=\"https://spid-testenv2:8088\">https://spid-testenv2:8088</saml:Issuer><ds:Signature"
                + " xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:SignedInfo><ds:CanonicalizationMethod"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/><ds:SignatureMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\"/><ds:Reference"
                + " URI=\"#id_451563f4726745384be4ab177e82c542baa99430\"><ds:Transforms><ds:Transform"
                + " Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/><ds:Transform"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/></ds:Transforms><ds:DigestMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\"/><ds:DigestValue>4cqgG29TSKgNLy2/1eFPXhd5WRVPxZBGcd8DgTvd5Fo=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>WqxM+y+vtZDcEaIaw2WfcuMuwXUeTOY9ZjaXwzHw+RE8uUr5s8BE1tpaodcKmmqSJK1JQYNr8AUV+W9V79EKfmNtFvfaf0WYeUee7Td7E24QqiyVHjr1YgfDWhSdItFLYJfQUkotj2BepbdwVQGY5yN0Rw6Fq98hgNOgsxty7g6oqxG1OXB4WJ2He20iOoYWQl8ApxlbU//hwnefFYe9ghDPy3rDbcNl3JetT07NR/+AzhKH4e+JCwKjTkdCBTW30fK4eiV9yBk74Lobip4hMaQhMaByl8egaU3A8AsnsZQuov2B6Wo2sDiQPjIulb8K3DOwFyL8PzEk8BB5YoAfwg==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIC7TCCAdWgAwIBAgIJAMbxPOoBth1LMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNV\n"
                + "BAYTAklUMB4XDTE4MDkwNDE0MDAxM1oXDTE4MTAwNDE0MDAxM1owDTELMAkGA1UE\n"
                + "BhMCSVQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJrW3y8Zd2jESP\n"
                + "XGMRY04cHC4Qfo3302HEY1C6x1aDfW7aR/tXzNplfdw8ZtZugSSmHZBxVrR8aA08\n"
                + "dUVbbtUw5qD0uAWKIeREqGfhM+J1STAMSI2/ZxA6t2fLmv8l1eRd1QGeRDm7yF9E\n"
                + "EKGY9iUZD3LJf2mWdVBAzzYlG23M769k+9JuGZxuviNWMjojgYRiQFgzypUJJQz+\n"
                + "Ihh3q7LMjjiQiiULVb9vnJg7UdU9Wf3xGRkxk6uiGP9SzWigSObUekYYQ4ZAI/sp\n"
                + "ILywgDxVMMtv/eVniUFKLABtljn5cE9zltECahPbm7wIuMJpDDu5GYHGdYO0j+K7\n"
                + "fhjvF2mzAgMBAAGjUDBOMB0GA1UdDgQWBBQEVmzA/L1/fd70ok+6xtDRF8A3HjAf\n"
                + "BgNVHSMEGDAWgBQEVmzA/L1/fd70ok+6xtDRF8A3HjAMBgNVHRMEBTADAQH/MA0G\n"
                + "CSqGSIb3DQEBCwUAA4IBAQCRMo4M4PqS0iLTTRWfikMF4hYMapcpmuna6p8aee7C\n"
                + "wTjS5y7y18RLvKTi9l8OI0dVkgokH8fq8/o13vMw4feGxro1hMeUilRtH52funrW\n"
                + "C+FgPrqk3o/8cZOnq+CqnFFDfILLiEb/PVJMddvTXgv2f9O6u17f8GmMLzde1yvY\n"
                + "Da1fG/Pi0fG2F0yw/CmtP8OTLSvxjPtJ+ZckGzZa9GotwHsoVJ+Od21OU2lOeCnO\n"
                + "jJOAbewHgqwkCB4O4AT5RM4ThAQtoU8QibjD1XDk/ZbEHdKcofnziDyl0V8gglP2\n"
                + "SxpzDaPX0hm4wgHk9BOtSikb72tfOw+pNfeSrZEr6ItQ\n"
                + "</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature>\n"
                + "    <saml:Subject>\n"
                + "      <saml:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://spid-testenv2:8088\">id_48129c2a9d5e9077422591baf495747cfda668c5</saml:NameID>\n"
                + "      <saml:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\n"
                + "        <saml:SubjectConfirmationData"
                + " Recipient=\"https://localhost:8000/assertionConsumerService\""
                + " NotOnOrAfter=\"2023-04-26T13:25:47Z\""
                + " InResponseTo=\"sha256-chG21HBOK-wJp2hHuYPrx7tAII2UGWVF-IFo0crUOtw\"/>\n"
                + "      </saml:SubjectConfirmation>\n"
                + "    </saml:Subject>\n"
                + "    <saml:Conditions NotBefore=\"2023-04-26T13:21:47Z\""
                + " NotOnOrAfter=\"2023-04-26T13:25:47Z\">\n"
                + "      <saml:AudienceRestriction>\n"
                + "        <saml:Audience>https://spid.agid.gov.it/cd</saml:Audience>\n"
                + "      </saml:AudienceRestriction>\n"
                + "    </saml:Conditions>\n"
                + "    <saml:AuthnStatement AuthnInstant=\"2023-04-26T13:23:47Z\""
                + " SessionIndex=\"id_2086da5272d65361b188f3bb66b9eacaf9c2e219\">\n"
                + "      <saml:AuthnContext>\n"
                + "       "
                + " <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL2</saml:AuthnContextClassRef>\n"
                + "      </saml:AuthnContext>\n"
                + "    </saml:AuthnStatement>\n"
                + "    <saml:AttributeStatement>\n"
                + "      <saml:Attribute Name=\"email\">\n"
                + "        <saml:AttributeValue"
                + " xsi:type=\"xs:string\">info@agid.gov.it</saml:AttributeValue>\n"
                + "      </saml:Attribute>\n"
                + "      <saml:Attribute Name=\"name\">\n"
                + "        <saml:AttributeValue"
                + " xsi:type=\"xs:string\">Mario</saml:AttributeValue>\n"
                + "      </saml:Attribute>\n"
                + "      <saml:Attribute Name=\"familyName\">\n"
                + "        <saml:AttributeValue"
                + " xsi:type=\"xs:string\">Bianchi</saml:AttributeValue>\n"
                + "      </saml:Attribute>\n"
                + "      <saml:Attribute Name=\"fiscalNumber\">\n"
                + "        <saml:AttributeValue"
                + " xsi:type=\"xs:string\">GDNNWA12H81Y874F</saml:AttributeValue>\n"
                + "      </saml:Attribute>\n"
                + "      <saml:Attribute Name=\"dateOfBirth\">\n"
                + "        <saml:AttributeValue"
                + " xsi:type=\"xs:date\">1991-12-12</saml:AttributeValue>\n"
                + "      </saml:Attribute>\n"
                + "    </saml:AttributeStatement>\n"
                + "  </saml:Assertion>\n"
                + "</samlp:Response>";

    private TestUtils() {}
}
