/* (C)2023 */
package it.pagopa.tech.lollipop.consumer;

public class TestUtils {

    public static final String VALID_FISCAL_CODE = "AAAAAA89S20I111X";
    public static final String VALID_JWK =
            "{  \"kty\": \"EC\",  \"crv\": \"P-256\",  \"x\":"
                    + " \"SVqB4JcUD6lsfvqMr-OKUNUphdNn64Eay60978ZlL74\",  \"y\":"
                    + " \"lf0u0pMj4lGAzZix5u4Cm5CMQIgMNpkwy163wtKYVKI\"}";
    public static final String VALID_SHA_256_ASSERTION_REF =
            "sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg";
    public static final String VALID_SHA_384_ASSERTION_REF =
            "sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw";
    public static final String VALID_SHA_512_ASSERTION_REF =
            "sha512-nX5CfUc5R-FoYKYZwvQMuc4Tt-heb7vHi_O-AMUSqHNVCw9kNaN2SVuN-DXtGXyUhrcVcQdCyY6FVzl_vyWXNA";
    public static final String EMPTY_ASSERTION_XML =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><root></root>";
    public static final String ASSERTION_XML_WITH_INVALID_PERIOD_DATE_FORMAT =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\"><saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\"><saml2:Conditions"
                + " NotBefore=\"2023-02-28\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\"><saml2:AudienceRestriction><saml2:Audience>https://app-backend.io.italia.it</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions></saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_EXPIRED_PERIOD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\"><saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\"><saml2:Conditions"
                + " NotBefore=\"2000-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\"><saml2:AudienceRestriction><saml2:Audience>https://app-backend.io.italia.it</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions></saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_ATTRIBUTE_TAG =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\"><saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\"><saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\"><saml2:AudienceRestriction><saml2:Audience>https://app-backend.io.italia.it</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions></saml2:Assertion></saml2p:Response>";

    public static final String ASSERTION_XML_WITHOUT_FISCAL_CODE =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">     "
                + " <saml2:Conditions NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">         <saml2:AudienceRestriction> "
                + "           <saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>    "
                + "     </saml2:AudienceRestriction>      </saml2:Conditions>\t       "
                + " <saml2:AttributeStatement>         <saml2:Attribute>         </saml2:Attribute>"
                + "      </saml2:AttributeStatement>   </saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_SUBJECTCONFIRMATIONDATA_TAG =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">     "
                + " <saml2:Conditions NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">         <saml2:AudienceRestriction> "
                + "           <saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>    "
                + "     </saml2:AudienceRestriction>      </saml2:Conditions>\t "
                + " <saml2:AttributeStatement>         <saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">            <saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>        "
                + " </saml2:Attribute>      </saml2:AttributeStatement>  "
                + " </saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_INVALID_INRESPONSETO_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"INVALIDsha-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_INRESPONSETO_SHA256_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_INRESPONSETO_SHA384_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_INRESPONSETO_SHA512_ALGORITHM =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha512-nX5CfUc5R-FoYKYZwvQMuc4Tt-heb7vHi_O-AMUSqHNVCw9kNaN2SVuN-DXtGXyUhrcVcQdCyY6FVzl_vyWXNA\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha512-nX5CfUc5R-FoYKYZwvQMuc4Tt-heb7vHi_O-AMUSqHNVCw9kNaN2SVuN-DXtGXyUhrcVcQdCyY6FVzl_vyWXNA\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_INSTANT_FIELD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\" Version=\"2.0\">\t"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITHOUT_ENTITY_ID_FIELD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t\t<saml2:Subject>\t"
                + "\t\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_INVALID_INSTANT_FORMAT =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"1680691737\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\" IssueInstant=\"1680691737\""
                + " Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer>"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_VALID_ENTITY_ID_FIELD =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer>"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String ASSERTION_XML_WITH_INVALID_SIGNATURE =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer><Signature"
                + " xmlns=\"http://www.w3.org/2000/09/xmldsig#\">\n"
                + "         <SignedInfo>\n"
                + "            <CanonicalizationMethod"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\" />\n"
                + "            <SignatureMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\" />\n"
                + "            <Reference URI=\"#_6b9580aa-08b1-4f19-8fb6-8b670d070bad\">\n"
                + "               <Transforms>\n"
                + "                  <Transform"
                + " Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\" />\n"
                + "                  <Transform"
                + " Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\" />\n"
                + "               </Transforms>\n"
                + "               <DigestMethod"
                + " Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\" />\n"
                + "              "
                + " <DigestValue>ViSjPfKj683dCuO7FdSzbQjw+vECYfoxgTeiVSgxr+I=</DigestValue>\n"
                + "            </Reference>\n"
                + "         </SignedInfo>\n"
                + "        "
                + " <SignatureValue>O9lmrtHPudDz2fzzNH3DQxWy2rlXE56G54Siq7OPMYwps/cyo3wKo7+PwMJYNhhz1l57OYJ5e/MF\n"
                + "               "
                + " ctVtYyl2rWo3QZOidWhg8WINIEqtFXIpk+ht5i2t3P1132/iL/gnY+fgemhnbOV/otEspHA4Wsio\n"
                + "               "
                + " I8xWjekAFlHBTOTtO9vzzqTtf+yalf+6pZmRLtOYrMMV4W3QZ2oLr7C2vTgcl5eVXJyGf0U8Y2bf\n"
                + "               "
                + " 7OPRHJNnVs4S8ztWQEwqZLFA1SvyCx1Nx6f+xd9lT7Lo1h81MRMdvRTk3rAaWYaqAmU9mxVnzsw4\n"
                + "                xaLjxR4rE2drY3eb+O8uHZbzFlOhPtaINRPILg==</SignatureValue>\n"
                + "         <KeyInfo>\n"
                + "            <X509Data>\n"
                + "              "
                + " <X509Certificate>MIIFgzCCA2ugAwIBAgIIJSppAZKg/XQwDQYJKoZIhvcNAQELBQAwZTELMAkGA1UEBhMCSVQxHjAc\n"
                + "                       "
                + " BgNVBAoMFVBvc3RlIEl0YWxpYW5lIFMucC5BLjEaMBgGA1UEYQwRVkFUSVQtMDExMTQ2MDEwMDYx\n"
                + "                       "
                + " GjAYBgNVBAMMEVBvc3RlIEl0YWxpYW5lIENBMB4XDTIxMDIxODExNDYzMVoXDTI0MDIxOTExNDYz\n"
                + "                       "
                + " MVowQzELMAkGA1UEBhMCSVQxHjAcBgNVBAoMFVBvc3RlIEl0YWxpYW5lIFMucC5BLjEUMBIGA1UE\n"
                + "                       "
                + " AwwLaWRwLXBvc3RlaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZFEtJoEHFAjpC\n"
                + "                       "
                + " aZcj5DVWrRDyaLZyu31XApslbo87CyWz61OJMtw6QQU0MdCtrYbtSJ6vJwx7/6EUjsZ3u4x3EPLd\n"
                + "                       "
                + " lkyiGOqukPwATv4c7TVOUVs5onIqTphM9b+AHRg4ehiMGesm/9d7RIaLuN79iPUvdLn6WP3idAfE\n"
                + "                       "
                + " w+rhJ/wYEQ0h1Xm5osNUgtWcBGavZIjLssWNrDDfJYxXH3QZ0kI6feEvLCJwgjXLGkBuhFehNhM4\n"
                + "                       "
                + " fhbX9iUCWwwkJ3JsP2++Rc/iTA0LZhiUsXNNq7gBcLAJ9UX2V1dWjTzBHevfHspzt4e0VgIIwbDR\n"
                + "                       "
                + " qsRtF8VUPSDYYbLoqwbLt18XAgMBAAGjggFXMIIBUzA/BggrBgEFBQcBAQQzMDEwLwYIKwYBBQUH\n"
                + "                       "
                + " MAGGI2h0dHA6Ly9wb3N0ZWNlcnQucG9zdGUuaXQvcGktb2NzcENBMB0GA1UdDgQWBBRL64pGUJHw\n"
                + "                       "
                + " Y7ok6cRMUgXvMBoLMjAfBgNVHSMEGDAWgBRs0025F7hHd0d+ULyAaELPZ7w/eTA+BgNVHSAENzA1\n"
                + "                       "
                + " MDMGCCtMMAEFAQEEMCcwJQYIKwYBBQUHAgEWGWh0dHA6Ly9wb3N0ZWNlcnQucG9zdGUuaXQwOAYD\n"
                + "                       "
                + " VR0fBDEwLzAtoCugKYYnaHR0cDovL3Bvc3RlY2VydC5wb3N0ZS5pdC9waS1DQS9jcmwuY3JsMA4G\n"
                + "                       "
                + " A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwJwYDVR0RBCAwHoEc\n"
                + "                       "
                + " aWRwLXBvc3RlaWRAcG9zdGVpdGFsaWFuZS5pdDANBgkqhkiG9w0BAQsFAAOCAgEAp0EhITlTx+cO\n"
                + "                       "
                + " aoXw//nBl6Q4y82MfSGfPJIw3ROV1z3tHBctaksi/RxAzyMD5beO2s8Q6lXx0sLMCcuUQmzHj3eJ\n"
                + "                       "
                + " bqn+6sIUr000dSlX/iPgVUc2dvPIZZg9xu38J8NvCfrtgAGY5iMVFMd3CZLFw0ybr+Bx/1K/NhQO\n"
                + "                       "
                + " 7jxn0RSGA1J4mM2syVhEDUODs9kz3T4kXYUofwwvPL1a9xB9RBqbp7plYtbBBdftEORUQrWzH1mz\n"
                + "                       "
                + " NO4nlFkX9qgVrgFIIJJT2KadHoop1r65O9ffncK14qpNo3eTsNDq3hRlteb7ylmlJ8CoakUWZeXD\n"
                + "                       "
                + " DP9ZboWxZkyp+9903OrToRvOgeWSc+YrqcRZOv7r6tTALTk4U9OTKDG9/eNWSGQqD7Qd/9rssfF0\n"
                + "                       "
                + " uJEGHnbsk/Hvdxn8apgWN1Zwt6tsT7f/DO0Pdlaso9g7PVy8R+B3VkWAh76uCcICIPFBluC/ljaH\n"
                + "                       "
                + " V8hI+VsCLpMClo83YMCEM6E6nAPD22+fDR/DF9P73P04yUvJVHx4cnHPrpxVrPbaJoKrr9mUOLFy\n"
                + "                       "
                + " VRekX78ZRgiFiKYDNsiq9+148oRy+VehpmBoQ+T2EPeDFQ8JJ4xT8H7qdyr1swSk/9Lu4K0kw/yC\n"
                + "                       "
                + " TSb9K/wCuiHiuoSB54rzJoQxz90gS868r/+JGahYwHY5dUh1RbA4g5N8H3TDThc=</X509Certificate>\n"
                + "            </X509Data>\n"
                + "         </KeyInfo>\n"
                + "      </Signature>\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha384-lqxC_2kqMdwiBWoD-Us63Fha6e3bE1Y3yUz8G6IJTldohJCIBVDfvS8acB3GJBhw\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";
    public static final String CERTIFICATE_TIM_LATEST =
            "MIID0jCCArqgAwIBAgIUXDUOKL3WuolxDw96Fk9es8rIt6kwDQYJKoZIhvcNAQELBQAwgYsxCzAJBgNVBAYTAklUMS4wLAYDVQQKDCVUZWxlY29tIEl0YWxpYSBUcnVzdCBUZWNobm9sb2dpZXMgc3JsMSgwJgYDVQQLDB9TZXJ2aXppIHBlciBsJ2lkZW50aXRhIGRpZ2l0YWxlMSIwIAYDVQQDDBlUSSBUcnVzdCBUZWNobm9sb2dpZXMgc3JsMB4XDTIxMTExMTE3MDMyMFoXDTI1MTExMDE3MDMyMFowgYsxCzAJBgNVBAYTAklUMS4wLAYDVQQKDCVUZWxlY29tIEl0YWxpYSBUcnVzdCBUZWNobm9sb2dpZXMgc3JsMSgwJgYDVQQLDB9TZXJ2aXppIHBlciBsJ2lkZW50aXRhIGRpZ2l0YWxlMSIwIAYDVQQDDBlUSSBUcnVzdCBUZWNobm9sb2dpZXMgc3JsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6sIS3+3iZSaAIyVywahlbpua2uJ/XmpV68P1e1STJpHoaj32STdHhqZnnb4Y/FshP1NUolzNolPXAYDmDduW1OnGndJZ+G9Hjh1PCkdiRw+p0FjhQAsGJkn8NdgTIHLJjqN1qQwtOsVGab8ScyA3mtmj3xKYuBhUoweuATzC7f5r7FfIoc3cy6N5lgrpZpfeAChxLwoHVjoAVgIBuemi6HAzmd4/BI06KzOcR7+dBVi4+uiseldxrJ5bhnjZKIwgkX14y9UA84Y+e+rMtyT8cT3XXi9NazZl5Ej5/bQPqqVsbg6tXzQSfEJD6JEjuYeC0RUKMS/EJn3hL5VLzTJ1NwIDAQABoywwKjAdBgNVHQ4EFgQUfctFZ8bRtmEvXPRlqgVDuggY/ZwwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEA0lszHadknPfE17IWGWsgvlXOdKMnWcl9H5rEYmsWwDB9FJG9XAZvPMcVv1kkWi6XZI/8N2Twhu1BdZkdvntDRscuck8wxxIpkRV7CwlcqNFZ/IwjDBxOBa8Q1J850p+qP8A9apsLLPUlu/oLygNDWIXzcOjMqnPkEP+XXUNYPto5iV+OyDzLLacCYqDDHcvDewWLmEjt35X967KcM+m7K2zGRLWfqcZPIjJJOkpNjgcs+MaisMrGDyOKiD16v0LpwVyIpTqXvDk7KHo8CUNXDxyLxZzB6WffgnOgjXTfU3vluweOx0qQy/VxIupDlNBKiZB4gnt1oAfnaMbqla9wcw==";
    public static final String ASSERTION_XML_TIM =
            "PHNhbWwycDpSZXNwb25zZSB4bWxuczpzYW1sMnA9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCIgRGVzdGluYXRpb249Imh0dHBzOi8vYXBwLWJhY2tlbmQuaW8uaXRhbGlhLml0L2Fzc2VydGlvbkNvbnN1bWVyU2VydmljZSIgSUQ9Il85YzA0YTI4ZDkzNWViNmMyODg0Njc4OTc0ZjA0OWZhNiIgSW5SZXNwb25zZVRvPSJzaGEyNTYtTUpDOTZQZzFUdWZEN0FNMWdTTW0xZ3JRUExFOGI1UjFJcjFKSmJaQlExSSIgSXNzdWVJbnN0YW50PSIyMDIzLTA0LTA0VDE1OjAxOjQ1Ljk3M1oiIFZlcnNpb249IjIuMCI+PHNhbWwyOklzc3VlciB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDplbnRpdHkiPmh0dHBzOi8vbG9naW4uaWQudGltLml0L2FmZndlYnNlcnZpY2VzL3B1YmxpYy9zYW1sMnNzbzwvc2FtbDI6SXNzdWVyPjxTaWduYXR1cmUgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPjxTaWduZWRJbmZvPjxDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+PFNpZ25hdHVyZU1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZHNpZy1tb3JlI3JzYS1zaGEyNTYiLz48UmVmZXJlbmNlIFVSST0iI185YzA0YTI4ZDkzNWViNmMyODg0Njc4OTc0ZjA0OWZhNiI+PFRyYW5zZm9ybXM+PFRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PFRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvVHJhbnNmb3Jtcz48RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8+PERpZ2VzdFZhbHVlPk1kRjE4aTNRVC9pdnBrdjdubkdlWms4N3hzYWpFWlY3d3Jrdm9IUy9KZGs9PC9EaWdlc3RWYWx1ZT48L1JlZmVyZW5jZT48L1NpZ25lZEluZm8+PFNpZ25hdHVyZVZhbHVlPk5TWCtWWCtMaXJYNzROQ0lQbGVxelIxeTIwZW5rVS9IQ2tKWlJmOUFCNEQvSkFJRUhSdWRxbmhyckQyb05OZ3lRNnltcktsSFVvQnpnbVhGWmIvUE8wa0pXTzVwbGhLY1AxakFhNlF4NTRNaHFqUnA2cmdhcGk2SlJGTXErbDVXeVVLSnRXMHBCdkpQYUVpMngxeG1HUHZzZU81ZkNEbnVpZHZEdXYydFVqRm1jZTY4bzRGWjF2dGprd0w3TExMNUNNTHc4dVNnWFNwK1lhOUNNQzJaYVl5aDNOaExsUktvazNuakVpd2d2ZTRWUURQRGZ0RmhnektHb25zM0FHcTQra2xPODBzaWF4WUl1Y1FKMVdxUmJKL3NzRUV5N3NOZXU3cXlhSmsrekpzVnA5cU5OL0RhM3lxTXp1bVRUMmtSZnNIL0tuWFJmTC9NQnNHNFNEVHY0QT09PC9TaWduYXR1cmVWYWx1ZT48S2V5SW5mbz48WDUwOURhdGE+PFg1MDlDZXJ0aWZpY2F0ZT5NSUlEMGpDQ0FycWdBd0lCQWdJVVhEVU9LTDNXdW9seER3OTZGazllczhySXQ2a3dEUVlKS29aSWh2Y05BUUVMQlFBd2dZc3hDekFKQmdOVkJBWVRBa2xVTVM0d0xBWURWUVFLRENWVVpXeGxZMjl0SUVsMFlXeHBZU0JVY25WemRDQlVaV05vYm05c2IyZHBaWE1nYzNKc01TZ3dKZ1lEVlFRTERCOVRaWEoyYVhwcElIQmxjaUJzSjJsa1pXNTBhWFJoSUdScFoybDBZV3hsTVNJd0lBWURWUVFEREJsVVNTQlVjblZ6ZENCVVpXTm9ibTlzYjJkcFpYTWdjM0pzTUI0WERUSXhNVEV4TVRFM01ETXlNRm9YRFRJMU1URXhNREUzTURNeU1Gb3dnWXN4Q3pBSkJnTlZCQVlUQWtsVU1TNHdMQVlEVlFRS0RDVlVaV3hsWTI5dElFbDBZV3hwWVNCVWNuVnpkQ0JVWldOb2JtOXNiMmRwWlhNZ2MzSnNNU2d3SmdZRFZRUUxEQjlUWlhKMmFYcHBJSEJsY2lCc0oybGtaVzUwYVhSaElHUnBaMmwwWVd4bE1TSXdJQVlEVlFRRERCbFVTU0JVY25WemRDQlVaV05vYm05c2IyZHBaWE1nYzNKc01JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNnNJUzMrM2laU2FBSXlWeXdhaGxicHVhMnVKL1htcFY2OFAxZTFTVEpwSG9hajMyU1RkSGhxWm5uYjRZL0ZzaFAxTlVvbHpOb2xQWEFZRG1EZHVXMU9uR25kSlorRzlIamgxUENrZGlSdytwMEZqaFFBc0dKa244TmRnVElITEpqcU4xcVF3dE9zVkdhYjhTY3lBM210bWozeEtZdUJoVW93ZXVBVHpDN2Y1cjdGZklvYzNjeTZONWxncnBacGZlQUNoeEx3b0hWam9BVmdJQnVlbWk2SEF6bWQ0L0JJMDZLek9jUjcrZEJWaTQrdWlzZWxkeHJKNWJobmpaS0l3Z2tYMTR5OVVBODRZK2Urck10eVQ4Y1QzWFhpOU5helpsNUVqNS9iUVBxcVZzYmc2dFh6UVNmRUpENkpFanVZZUMwUlVLTVMvRUpuM2hMNVZMelRKMU53SURBUUFCb3l3d0tqQWRCZ05WSFE0RUZnUVVmY3RGWjhiUnRtRXZYUFJscWdWRHVnZ1kvWnd3Q1FZRFZSMFRCQUl3QURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQTBsc3pIYWRrblBmRTE3SVdHV3NndmxYT2RLTW5XY2w5SDVyRVltc1d3REI5RkpHOVhBWnZQTWNWdjFra1dpNlhaSS84TjJUd2h1MUJkWmtkdm50RFJzY3Vjazh3eHhJcGtSVjdDd2xjcU5GWi9Jd2pEQnhPQmE4UTFKODUwcCtxUDhBOWFwc0xMUFVsdS9vTHlnTkRXSVh6Y09qTXFuUGtFUCtYWFVOWVB0bzVpVitPeUR6TExhY0NZcURESGN2RGV3V0xtRWp0MzVYOTY3S2NNK203SzJ6R1JMV2ZxY1pQSWpKSk9rcE5qZ2NzK01haXNNckdEeU9LaUQxNnYwTHB3VnlJcFRxWHZEazdLSG84Q1VOWER4eUx4WnpCNldmZmduT2dqWFRmVTN2bHV3ZU94MHFReS9WeEl1cERsTkJLaVpCNGdudDFvQWZuYU1icWxhOXdjdz09PC9YNTA5Q2VydGlmaWNhdGU+PC9YNTA5RGF0YT48L0tleUluZm8+PC9TaWduYXR1cmU+PHNhbWwycDpTdGF0dXM+PHNhbWwycDpTdGF0dXNDb2RlIFZhbHVlPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6c3RhdHVzOlN1Y2Nlc3MiLz48L3NhbWwycDpTdGF0dXM+PHNhbWwyOkFzc2VydGlvbiB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgSUQ9Il9jMjYwYjI2NzNlYzMwZjJjNzI0YjI5NDM2NTFiOWEyYiIgSXNzdWVJbnN0YW50PSIyMDIzLTA0LTA0VDE1OjAxOjQ1Ljk3M1oiIFZlcnNpb249IjIuMCI+PHNhbWwyOklzc3VlciBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OmVudGl0eSI+aHR0cHM6Ly9sb2dpbi5pZC50aW0uaXQvYWZmd2Vic2VydmljZXMvcHVibGljL3NhbWwyc3NvPC9zYW1sMjpJc3N1ZXI+PFNpZ25hdHVyZSB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PFNpZ25lZEluZm8+PENhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIvPjxSZWZlcmVuY2UgVVJJPSIjX2MyNjBiMjY3M2VjMzBmMmM3MjRiMjk0MzY1MWI5YTJiIj48VHJhbnNmb3Jtcz48VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz48VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+PC9UcmFuc2Zvcm1zPjxEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNzaGEyNTYiLz48RGlnZXN0VmFsdWU+d2tlS0V1OWpFOGNaeFpVM3hWcWZEVURWVHpCUHZjL1FERXJRNXpRRWk3Yz08L0RpZ2VzdFZhbHVlPjwvUmVmZXJlbmNlPjwvU2lnbmVkSW5mbz48U2lnbmF0dXJlVmFsdWU+NWlUQ3o5WjdCT1d5QzBPZE56M2RNMXI1RG1yOTliamtvejZWMlJUVmJTNE5UUnB5UmVkb3ZqNHBhRmxXd0Z4Ris4eWNDNTJlUXRmVDk3Tk5HVExMRlJRYTMrODVWbHVqeFdWZmhDUks1aEJxV1VXZVFiUnl6YitmWlhJSEgxTE5ENTlkVUcrWHlDcDl1Z1lzbi9JZjJySGoxTUdxYnMvZnZaU25HeU16RzRrVXpSa0lXREl4eWdLSXNCYTREQUc0bms5MGNVRTBlQVRQdURDblhNbkEyWTMvWlJWN3lCalpXbUorZ3F1ZHExaWowUDJJL29FUVdIWW1yVTV1bkhIZTI0MmlmUTRpYkdydy93cWRpa1UvSDA1M0JHZEFFaFluTVByYWpPV1Z5SmhoYnlTdCsycmpDZ0xjeWZMWG5xV3FUVS9IdE5CSGNQWGhVK0RaL1Q5MzNBPT08L1NpZ25hdHVyZVZhbHVlPjxLZXlJbmZvPjxYNTA5RGF0YT48WDUwOUNlcnRpZmljYXRlPk1JSUQwakNDQXJxZ0F3SUJBZ0lVWERVT0tMM1d1b2x4RHc5NkZrOWVzOHJJdDZrd0RRWUpLb1pJaHZjTkFRRUxCUUF3Z1lzeEN6QUpCZ05WQkFZVEFrbFVNUzR3TEFZRFZRUUtEQ1ZVWld4bFkyOXRJRWwwWVd4cFlTQlVjblZ6ZENCVVpXTm9ibTlzYjJkcFpYTWdjM0pzTVNnd0pnWURWUVFMREI5VFpYSjJhWHBwSUhCbGNpQnNKMmxrWlc1MGFYUmhJR1JwWjJsMFlXeGxNU0l3SUFZRFZRUUREQmxVU1NCVWNuVnpkQ0JVWldOb2JtOXNiMmRwWlhNZ2MzSnNNQjRYRFRJeE1URXhNVEUzTURNeU1Gb1hEVEkxTVRFeE1ERTNNRE15TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVM0d0xBWURWUVFLRENWVVpXeGxZMjl0SUVsMFlXeHBZU0JVY25WemRDQlVaV05vYm05c2IyZHBaWE1nYzNKc01TZ3dKZ1lEVlFRTERCOVRaWEoyYVhwcElIQmxjaUJzSjJsa1pXNTBhWFJoSUdScFoybDBZV3hsTVNJd0lBWURWUVFEREJsVVNTQlVjblZ6ZENCVVpXTm9ibTlzYjJkcFpYTWdjM0pzTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE2c0lTMyszaVpTYUFJeVZ5d2FobGJwdWEydUovWG1wVjY4UDFlMVNUSnBIb2FqMzJTVGRIaHFabm5iNFkvRnNoUDFOVW9sek5vbFBYQVlEbURkdVcxT25HbmRKWitHOUhqaDFQQ2tkaVJ3K3AwRmpoUUFzR0prbjhOZGdUSUhMSmpxTjFxUXd0T3NWR2FiOFNjeUEzbXRtajN4S1l1QmhVb3dldUFUekM3ZjVyN0ZmSW9jM2N5Nk41bGdycFpwZmVBQ2h4THdvSFZqb0FWZ0lCdWVtaTZIQXptZDQvQkkwNkt6T2NSNytkQlZpNCt1aXNlbGR4cko1YmhualpLSXdna1gxNHk5VUE4NFkrZStyTXR5VDhjVDNYWGk5TmF6Wmw1RWo1L2JRUHFxVnNiZzZ0WHpRU2ZFSkQ2SkVqdVllQzBSVUtNUy9FSm4zaEw1Vkx6VEoxTndJREFRQUJveXd3S2pBZEJnTlZIUTRFRmdRVWZjdEZaOGJSdG1FdlhQUmxxZ1ZEdWdnWS9ad3dDUVlEVlIwVEJBSXdBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBMGxzekhhZGtuUGZFMTdJV0dXc2d2bFhPZEtNbldjbDlINXJFWW1zV3dEQjlGSkc5WEFadlBNY1Z2MWtrV2k2WFpJLzhOMlR3aHUxQmRaa2R2bnREUnNjdWNrOHd4eElwa1JWN0N3bGNxTkZaL0l3akRCeE9CYThRMUo4NTBwK3FQOEE5YXBzTExQVWx1L29MeWdORFdJWHpjT2pNcW5Qa0VQK1hYVU5ZUHRvNWlWK095RHpMTGFjQ1lxRERIY3ZEZXdXTG1FanQzNVg5NjdLY00rbTdLMnpHUkxXZnFjWlBJakpKT2twTmpnY3MrTWFpc01yR0R5T0tpRDE2djBMcHdWeUlwVHFYdkRrN0tIbzhDVU5YRHh5THhaekI2V2ZmZ25PZ2pYVGZVM3ZsdXdlT3gwcVF5L1Z4SXVwRGxOQktpWkI0Z250MW9BZm5hTWJxbGE5d2N3PT08L1g1MDlDZXJ0aWZpY2F0ZT48L1g1MDlEYXRhPjwvS2V5SW5mbz48L1NpZ25hdHVyZT48c2FtbDI6U3ViamVjdD48c2FtbDI6TmFtZUlEIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6dHJhbnNpZW50IiBOYW1lUXVhbGlmaWVyPSJodHRwczovL2xvZ2luLmlkLnRpbS5pdC9hZmZ3ZWJzZXJ2aWNlcy9wdWJsaWMvc2FtbDJzc28iPl80OTJlNDQyNGVjOTVjNzU5MWViMTY5MGJjOTk3ZDIwMzwvc2FtbDI6TmFtZUlEPjxzYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+PHNhbWwyOlN1YmplY3RDb25maXJtYXRpb25EYXRhIEluUmVzcG9uc2VUbz0ic2hhMjU2LU1KQzk2UGcxVHVmRDdBTTFnU01tMWdyUVBMRThiNVIxSXIxSkpiWkJRMUkiIE5vdE9uT3JBZnRlcj0iMjAyMy0wNC0wNFQxNTowMjoxNS45NzNaIiBSZWNpcGllbnQ9Imh0dHBzOi8vYXBwLWJhY2tlbmQuaW8uaXRhbGlhLml0L2Fzc2VydGlvbkNvbnN1bWVyU2VydmljZSIvPjwvc2FtbDI6U3ViamVjdENvbmZpcm1hdGlvbj48L3NhbWwyOlN1YmplY3Q+PHNhbWwyOkNvbmRpdGlvbnMgTm90QmVmb3JlPSIyMDIzLTA0LTA0VDE1OjAxOjQ0Ljk3M1oiIE5vdE9uT3JBZnRlcj0iMjAyMy0wNC0wNFQxNTowMjoxNS45NzNaIj48c2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj48c2FtbDI6QXVkaWVuY2U+aHR0cHM6Ly9hcHAtYmFja2VuZC5pby5pdGFsaWEuaXQ8L3NhbWwyOkF1ZGllbmNlPjwvc2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj48L3NhbWwyOkNvbmRpdGlvbnM+PHNhbWwyOkF1dGhuU3RhdGVtZW50IEF1dGhuSW5zdGFudD0iMjAyMy0wNC0wNFQxNTowMTo0NS45NzNaIj48c2FtbDI6QXV0aG5Db250ZXh0PjxzYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj5odHRwczovL3d3dy5zcGlkLmdvdi5pdC9TcGlkTDI8L3NhbWwyOkF1dGhuQ29udGV4dENsYXNzUmVmPjwvc2FtbDI6QXV0aG5Db250ZXh0Pjwvc2FtbDI6QXV0aG5TdGF0ZW1lbnQ+PHNhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudD48c2FtbDI6QXR0cmlidXRlIEZyaWVuZGx5TmFtZT0iRGF0YSBkaSBuYXNjaXRhIiBOYW1lPSJkYXRlT2ZCaXJ0aCI+PHNhbWwyOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzOmRhdGUiPjE5ODctMDktMTQ8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjxzYW1sMjpBdHRyaWJ1dGUgRnJpZW5kbHlOYW1lPSJJbmRpcml6em8gZGkgcG9zdGEgZWxldHRyb25pY2EiIE5hbWU9ImVtYWlsIj48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj5waWV0cm8uc3Ryb2lhQGdtYWlsLmNvbTwvc2FtbDI6QXR0cmlidXRlVmFsdWU+PC9zYW1sMjpBdHRyaWJ1dGU+PHNhbWwyOkF0dHJpYnV0ZSBGcmllbmRseU5hbWU9IkNvZ25vbWUiIE5hbWU9ImZhbWlseU5hbWUiPjxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTp0eXBlPSJ4czpzdHJpbmciPlN0cm9pYTwvc2FtbDI6QXR0cmlidXRlVmFsdWU+PC9zYW1sMjpBdHRyaWJ1dGU+PHNhbWwyOkF0dHJpYnV0ZSBGcmllbmRseU5hbWU9IkNvZGljZSBmaXNjYWxlIiBOYW1lPSJmaXNjYWxOdW1iZXIiPjxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTp0eXBlPSJ4czpzdHJpbmciPlRJTklULVNUUlBUUjg3UDE0RTMzNVY8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjxzYW1sMjpBdHRyaWJ1dGUgRnJpZW5kbHlOYW1lPSJOb21lIiBOYW1lPSJuYW1lIj48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj5QaWV0cm88L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjwvc2FtbDI6QXR0cmlidXRlU3RhdGVtZW50Pjwvc2FtbDI6QXNzZXJ0aW9uPjwvc2FtbDJwOlJlc3BvbnNlPg==";

    private TestUtils() {}
}
