name: Check Build and Anchore on PR

on:
  pull_request:
  
env:
  DOCKERFILE: Dockerfile.test-only

jobs:
  pr_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checkout project sources
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      with:
        fetch-depth: 0    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
    - name: Make gradlew executable
      run: chmod +x ./gradlew  
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build . --file ${{ env.DOCKERFILE }} --tag localbuild/testimage:latest
    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      id: scan
      with:
        image: "localbuild/testimage:latest"
        fail-build: true
        severity-cutoff: "high"
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
